//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaiisanji
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string Post { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public int Age { get; set; }
        public string Phone_number { get; set; }
        public string Gender { get; set; }
        public string salary { get; set; }
        public int ID { get; set; }
    
        public virtual login login1 { get; set; }
        public virtual login login2 { get; set; }
    }
}
