//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaiisanji
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clinicEntities6 : DbContext
    {
        public clinicEntities6()
            : base("name=clinicEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> login { get; set; }
        public virtual DbSet<insurence> insurence { get; set; }
        public virtual DbSet<Nobat> Nobat { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<payment> payment { get; set; }
        public virtual DbSet<SicknessCosts> SicknessCosts { get; set; }
        public virtual DbSet<ReceptionIncome> ReceptionIncome { get; set; }
    }
}
