//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaiisanji
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.Nobat = new HashSet<Nobat>();
        }
    
        public string Fname { get; set; }
        public string Lname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Phone_Number { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Explain { get; set; }
        public int File_number { get; set; }
        public Nullable<int> InsurenceID { get; set; }
        public string F_date { get; set; }
        public string L_date { get; set; }
    
        public virtual insurence insurence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nobat> Nobat { get; set; }
    }
}
