//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaiisanji
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int PayID { get; set; }
        public string Cost { get; set; }
        public int PatientID { get; set; }
        public int PaymentDc { get; set; }
        public string PayInsurence { get; set; }
    }
}
