//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace binaiisanji
{
    using System;
    using System.Collections.Generic;
    
    public partial class SicknessCosts
    {
        public string SicknessID { get; set; }
        public string SicknessName { get; set; }
        public string SicknessCosts1 { get; set; }
    }
}
